Repository getAlby/lightning-browser-extension, pull requests merged in 2021-12, with the labels that each got.

#349 Add logos to new account screen
  src/app/components/LinkButton/index.tsx
  src/app/screens/Onboard/ChooseConnector/index.tsx
  src/custom.d.ts
  static/assets/icons/alby.png
  static/assets/icons/lnbits.png
  static/assets/icons/lnd.png
  static/assets/icons/lndhub.png
Labels: design, frontend

#455 Add BitcoinTV enhancement
  src/extension/content-script/batteries/Peertube.ts
  src/extension/content-script/batteries/index.ts
Labels: enhancement

#471 Check all ⚡️emojis in the twitter bio
  src/extension/content-script/batteries/Twitter.ts
  tsconfig.json
Labels: bug

#360 Initial draft of dark mode for feedback
  src/app/components/AccountMenu/index.tsx
  src/app/components/AllowanceMenu/index.tsx
  src/app/components/Button/index.tsx
  src/app/components/Card/index.jsx
  src/app/components/Form/Input/index.tsx
  src/app/components/Header/index.tsx
  src/app/components/LinkButton/index.tsx
  src/app/components/Menu/MenuDivider.tsx
  src/app/components/Menu/MenuItemButton.tsx
  src/app/components/Menu/MenuList.tsx
  src/app/components/Menu/MenuSubheader.tsx
  src/app/components/Navbar/Navbar.tsx
  src/app/components/Navbar/NavbarLink.tsx
  src/app/components/PaymentSummary.tsx
  src/app/components/PublishersTable/index.tsx
  src/app/components/QrcodeScanner/index.tsx
  src/app/components/Steps/index.jsx
  src/app/components/TransactionsTable/index.tsx
  src/app/components/UserMenu/index.tsx
  src/app/router/Welcome/Welcome.jsx
  src/app/screens/ConfirmPayment/index.jsx
  src/app/screens/Enable/index.jsx
  src/app/screens/Home/index.jsx
  src/app/screens/LNURLAuth.tsx
  src/app/screens/LNURLPay.tsx
  src/app/screens/Onboard/ChooseConnector/index.tsx
  src/app/screens/Onboard/ConnectLnbits/index.tsx
  src/app/screens/Onboard/ConnectLnd/index.tsx
  src/app/screens/Onboard/ConnectLndHub/index.tsx
  src/app/screens/Onboard/Intro/features.jsx
  src/app/screens/Onboard/Intro/index.jsx
  src/app/screens/Onboard/NewWallet/index.tsx
  src/app/screens/Onboard/SetPassword/index.jsx
  src/app/screens/Onboard/TestConnection/index.jsx
  src/app/screens/Options/ChooseConnector/index.jsx
  src/app/screens/Options/TestConnection/index.jsx
  src/app/screens/Publisher.tsx
  src/app/screens/Publishers.tsx
  src/app/screens/Receive.tsx
  src/app/screens/Send.tsx
  src/app/screens/Settings.tsx
  src/app/screens/Unlock/index.jsx
  static/views/options.html
  static/views/popup.html
  static/views/prompt.html
  static/views/welcome.html
  tailwind.config.js
Labels: design, frontend
