Repository getAlby/lightning-browser-extension, pull requests merged in 2021-11, with the labels that each got.

#393 feat: disallow horizontal scrollbar in popup
  static/views/popup.html
Labels: chore

#370 Use Alby as extension icon
  src/extension/background-script/actions/setup/setIcon.js
  src/extension/background-script/index.js
  src/manifest.json
  static/assets/icons/alby_icon_blue_128x128.png
  static/assets/icons/alby_icon_blue_128x128.svg
  static/assets/icons/alby_icon_blue_16x16.png
  static/assets/icons/alby_icon_blue_16x16.svg
  static/assets/icons/alby_icon_blue_32x32.png
  static/assets/icons/alby_icon_blue_32x32.svg
  static/assets/icons/alby_icon_blue_48x48.png
  static/assets/icons/alby_icon_blue_48x48.svg
  static/assets/icons/alby_icon_blue_64x64.png
  static/assets/icons/alby_icon_blue_64x64.svg
  static/assets/icons/alby_icon_sleeping_128x128.png
  static/assets/icons/alby_icon_sleeping_128x128.svg
  static/assets/icons/alby_icon_sleeping_16x16.png
  static/assets/icons/alby_icon_sleeping_16x16.svg
  static/assets/icons/alby_icon_sleeping_32x32.png
  static/assets/icons/alby_icon_sleeping_32x32.svg
  static/assets/icons/alby_icon_sleeping_48x48.png
  static/assets/icons/alby_icon_sleeping_48x48.svg
  static/assets/icons/alby_icon_sleeping_64x64.png
  static/assets/icons/alby_icon_sleeping_64x64.svg
  static/assets/icons/alby_icon_yellow_128x128.png
  static/assets/icons/alby_icon_yellow_128x128.svg
  static/assets/icons/alby_icon_yellow_16x16.jpg
  static/assets/icons/alby_icon_yellow_16x16.png
  static/assets/icons/alby_icon_yellow_16x16.svg
  static/assets/icons/alby_icon_yellow_32x32.png
  static/assets/icons/alby_icon_yellow_32x32.svg
  static/assets/icons/alby_icon_yellow_48x48.png
  static/assets/icons/alby_icon_yellow_48x48.svg
  static/assets/icons/alby_icon_yellow_64x64.png
  static/assets/icons/alby_icon_yellow_64x64.svg
  static/assets/icons/satsymbol-blue-128.png
  static/assets/icons/satsymbol-blue-16.png
  static/assets/icons/satsymbol-blue-32.png
  static/assets/icons/satsymbol-blue-48.png
  static/assets/icons/satsymbol-blue.png
  static/views/popup.html
Labels: design

#384 React Router v6 + Auth Flow
  package.json
  src/app/components/AccountMenu/index.tsx
  src/app/components/Navbar/NavbarLink.tsx
  src/app/components/UserMenu/index.tsx
  src/app/context/AuthContext.tsx
  src/app/router/Options/Options.jsx
  src/app/router/Popup/Popup.jsx
  src/app/router/Prompt/Prompt.jsx
  src/app/router/RequireAuth.tsx
  src/app/router/Welcome/Welcome.jsx
  src/app/screens/Home/index.jsx
  src/app/screens/LNURLPay.tsx
  src/app/screens/Onboard/ChooseConnector/index.tsx
  src/app/screens/Onboard/ConnectLnbits/index.tsx
  src/app/screens/Onboard/ConnectLnd/index.tsx
  src/app/screens/Onboard/ConnectLndHub/index.tsx
  src/app/screens/Onboard/Intro/index.jsx
  src/app/screens/Onboard/NewWallet/index.tsx
  src/app/screens/Onboard/SetPassword/index.jsx
  src/app/screens/Onboard/TestConnection/index.jsx
  src/app/screens/Options/ChooseConnector/index.jsx
  src/app/screens/Options/TestConnection/index.jsx
  src/app/screens/Publisher.tsx
  src/app/screens/Publishers.tsx
  src/app/screens/Receive.tsx
  src/app/screens/Send.tsx
  src/app/screens/Unlock/index.jsx
  src/extension/background-script/actions/accounts/unlock.js
  yarn.lock
Labels: chore

#386 Add optional debug mode
  src/extension/background-script/index.js
Labels: chore

#407 [Fix] Broken Storybook due to react-router 6 upgrade
  src/app/components/AccountMenu/AccountMenu.stories.tsx
  src/app/components/UserMenu/UserMenu.stories.tsx
Labels: bug

#406 Upgrade loading skeleton [breaking changes]
  .storybook/preview.js
  package.json
  src/app/router/Options/index.jsx
  src/app/router/Popup/index.jsx
  src/app/router/Prompt/index.jsx
  src/app/router/Welcome/index.jsx
  yarn.lock
Labels: chore

#405 Upgrade eslint
  package.json
  yarn.lock
Labels: chore
