Repository getAlby/lightning-browser-extension, pull requests merged in 2022-05, with the labels that each got.

#835 feat: add fee amount to tx table
  src/app/components/TransactionsTable/index.tsx
  src/types.ts
Labels: enhancement, frontend

#870 feat: add myNode and raspiblitz videos to connectors
  src/app/screens/connectors/ConnectMyNode/index.tsx
  src/app/screens/connectors/ConnectRaspiBlitz/index.tsx
Labels: enhancement, frontend

#898 chore(deps): copy-webpack-plugin v11
  .node-version
  .nvmrc
  package.json
  yarn.lock
Labels: dependencies

#916 refactor: remove connector badge from accounts dropdown
  src/app/components/AccountMenu/index.tsx
Labels: enhancement, frontend, user feedback

#948 feat: update alerts to use new toast component
  src/app/components/DevMenu/index.tsx
  src/app/context/AuthContext.tsx
  src/app/screens/Home/index.tsx
  src/app/screens/Settings.tsx
  src/app/screens/connectors/ConnectCitadel/index.tsx
  src/app/screens/connectors/ConnectEclair/index.tsx
  src/app/screens/connectors/ConnectGaloy/index.tsx
  src/app/screens/connectors/ConnectLnbits/index.tsx
  src/app/screens/connectors/ConnectLnd/index.tsx
  src/app/screens/connectors/ConnectLndHub/index.tsx
  src/app/screens/connectors/ConnectMyNode/index.tsx
  src/app/screens/connectors/ConnectRaspiBlitz/index.tsx
  src/app/screens/connectors/ConnectStart9/index.tsx
  src/app/screens/connectors/ConnectUmbrel/index.tsx
  src/app/screens/connectors/NewWallet/index.tsx
Labels: enhancement, frontend, chore
