Repository getAlby/lightning-browser-extension, pull requests merged in 2022-10, with the labels that each got.

#1575 fix: Remove brackets from success screen
  src/app/screens/LNURLPay/index.tsx
Labels: bug

#1595 fix: amount-input changes value on scroll
  src/app/components/form/DualCurrencyField/index.tsx
Labels: hacktoberfest, hacktoberfest-accepted

#1590 feat: add btcmap to the website directory
  src/app/screens/Publishers/websites.json
Labels: enhancement, frontend
